{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.hktk",
    "module": "hktk-sdk",
    "version": "1.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "hktk-sdk-1.3.12.aar",
          "url": "hktk-sdk-1.3.12.aar",
          "size": 64541,
          "sha512": "7718c51ce6da5618e2a895b609dbffb944f21665f8b44c064c77f580e28fd9db47fdef263a86cec3b6930be7512eb781b1f67432f5742c267a594f843971717a",
          "sha256": "122df290b95bcfb431f8b83e32461e447d6a76f79c87f2f36be682c75ee626ec",
          "sha1": "0ba54222e018bed04c8857cb691e5dda0aa31541",
          "md5": "a99594737f0a4b03303a4c53d9fe1657"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240303"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "hktk-sdk-1.3.12.aar",
          "url": "hktk-sdk-1.3.12.aar",
          "size": 64541,
          "sha512": "7718c51ce6da5618e2a895b609dbffb944f21665f8b44c064c77f580e28fd9db47fdef263a86cec3b6930be7512eb781b1f67432f5742c267a594f843971717a",
          "sha256": "122df290b95bcfb431f8b83e32461e447d6a76f79c87f2f36be682c75ee626ec",
          "sha1": "0ba54222e018bed04c8857cb691e5dda0aa31541",
          "md5": "a99594737f0a4b03303a4c53d9fe1657"
        }
      ]
    }
  ]
}
