{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.hktk",
    "module": "hktk-sdk",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "hktk-sdk-1.3.10.aar",
          "url": "hktk-sdk-1.3.10.aar",
          "size": 64546,
          "sha512": "48794fc84a6ca8c690d747a03de0749da5052734d388202c031e1b4040c7fac0ea0aadcf187b1ecf6218207b4f7e333b80ca8b8977f17a1349d9b4a057b46a36",
          "sha256": "d4ac6b86e4a6b766d4387b281904e0aa2311e6cc9ae0c494f933fa5308e38551",
          "sha1": "aa5c5214bc41a412e44bfc8faaac48175de0924e",
          "md5": "4da3af453003e6b1f7df8444bd354a34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240303"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "hktk-sdk-1.3.10.aar",
          "url": "hktk-sdk-1.3.10.aar",
          "size": 64546,
          "sha512": "48794fc84a6ca8c690d747a03de0749da5052734d388202c031e1b4040c7fac0ea0aadcf187b1ecf6218207b4f7e333b80ca8b8977f17a1349d9b4a057b46a36",
          "sha256": "d4ac6b86e4a6b766d4387b281904e0aa2311e6cc9ae0c494f933fa5308e38551",
          "sha1": "aa5c5214bc41a412e44bfc8faaac48175de0924e",
          "md5": "4da3af453003e6b1f7df8444bd354a34"
        }
      ]
    }
  ]
}
